### ISSUE TITLE
how to keep subwasm in sync with subxt?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [chevdor/subwasm#69] opened 2023-05-09 15:53 UTC
```
subwasm --version
subwasm get wss://rpc.composable.finance:443  --output=a.wasm
subwasm metadata --format=scale a.wasm > a.scale
~/.cargo/bin/subxt codegen --file=a.scale
```

gives
```
dz@pop-os:~/github.com/ComposableFi/composable/submetrics$ subwasm --version
subwasm get wss://rpc.composable.finance:443  --output=a.wasm
subwasm metadata --format=scale a.wasm > a.scale
~/.cargo/bin/subxt codegen --file=a.scale
subwasm v0.19.2
The application panicked (crashed).
Message:  Unsupported metadata version V12(OpaqueMetadata([115, 112, 95, 99, 111, 114, 101]))
Location: /home/dz/.cargo/registry/src/github.com-1ecc6299db9ec823/subxt-codegen-0.28.0/src/api/mod.rs:167

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
dz@pop-os:~/github.com/ComposableFi/composable/submetrics$ 
```

```
dz@pop-os:~/github.com/ComposableFi/composable/submetrics$ ~/.cargo/bin/subxt version
subxt-cli 0.28.0-unknown
```

**Comment by chevdor** [comment] 2023-05-09 16:38
ok, I think your first commands can be summarized as:
```
subwasm metadata wss://rpc.composable.finance:443  --format=scale > a.scale
```
 andf that works fine.

I see your error running:
```
~/.cargo/bin/subxt codegen --file=a.scale
```

but that seems to be coming from `subxt`. So the issue is either:
- what we pass to subxt (it reports V12 btw...)
- an old version of subxt
- an issue with subxt (that would be to report in the subxt repo then)

My version of subxt is probably not the freshest.
What does this command return for you: `~/.cargo/bin/subxt version` ?

**Comment by chevdor** [comment] 2023-05-09 16:39
The report of V12 is rather strange since:
```
subwasm info wss://rpc.composable.finance:443            
[2023-05-09T16:39:24Z INFO  subwasm] ⏱️  Loading WASM from Chain(OnchainBlock { endpoint: WebSocket("wss://rpc.composable.finance:443"), block_ref: None })
🏋️  Runtime size:             1.523 MB (1,597,047 bytes) 
🗜  Compressed:               Yes, 78.46%
✨ Reserved meta:            OK - [6D, 65, 74, 61]
🎁 Metadata version:         V14
🔥 Core version:             composable-10020 (composable-3.tx2.au1)
🗳️  system.setCode hash:      0xe5bc4837293aa2b12bf3def13e5622c43fbd6c467f62167ef8b177cecddf598c
🗳️  authorizeUpgrade hash:    0xccef5fab27dde391bbbaffc390e467fed3b80c83c255785023c4d627f73cd5f3
🗳️  Blake2-256 hash:          0x47ba47d4824fd30328f70f64b056d4e36e3b75594d6f590e1b85e90a65f9a63a
📦 IPFS:                     https://www.ipfs.io/ipfs/QmeeFjoJeWvZstf36wMbVM2LuTpUyGwX8qks3jhseTrepU
```

**Comment by chevdor** [comment] 2023-05-10 07:53
After some testing, I can confirm that the issue is not on the `subxt` side. 
The scale export from subwasm does not match what `subxt` uses.
My suspicion is that we export with one layer of wrapping missing/extra.

**Comment by chevdor** [comment] 2023-05-10 08:35
This issue will be fixed in a few moments.

**Closed** 2023-05-10 09:03 UTC

**Comment by dzmitry-lahoda** [comment] 2023-05-10 09:45
oh. thank you. i used subwasm as subxt has no option to get scale from local wasm. we are nix and our chain not warp yet, so prefer local.

**Comment by chevdor** [comment] 2023-05-10 10:24
Indeed, that totally makes sense.
The fix is not released in a new version yet but if you build from master, you should have a working solution already.
